before_script:
- npm install -g bower grunt-cli
- bower install
language: node_js
node_js:
- '0.10'
services: mongodb
HEROKU_URL:
  secure: OLat3Gg2QSuvpdXrFqJUHw3mYfrqbskotOgj1NNyww6d/zz7wfEldYvGvvmF1sU0MOJaiKz6Eqbbvb5S2ZU/uyr3oAOhcXsoc2gohmA4rqvFy4DOp6ZYvyatAgJts68uhq5k7/psIkXkEDnRUkTdFmJEJyLu9yjjW/Qiaox6J2o=
HEROKU_USER_NAME:
  secure: HSYdJjN/EBXFDisCbkmxQPkWHTVu1SS1RfM7Zvc+Qba/nIe/7eR+YimoGa1486Y+a87rK32e+/AJy48HgS5eRU7aWtNZ/ay9Vidb4GM8M6a0GqzwM1YYVxLFYY9c+yEle60gqgtg1nj4OlpA14AwKdLr0V2s5k92/l1ZycYtu8g=
HEROKU_USER_EMAIL:
  secure: NlASSllTNg8RFxD2TrnmRkLarsb2L/UI7qvOu3AEuE/Ix93c9nidhuivE55JOTbuVZncfr1AG1R67RUFjiVzldIE/pWrvL6rla4Os34QjmTuRDxYqkBdCwktypTEYhZVBtUzEIWmp7sp8WfEFXHCNzZz0GdHtKVFVI5YPe+Tr48=
after_success: "./deploy_heroku.sh"